# Generated by Django 3.1.3 on 2020-11-12 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('bg_name', models.CharField(max_length=20, primary_key=True)),
                ('bg_race', models.CharField(max_length=15)),
                ('bg_age', models.IntegerField(default=0)),
                ('bg_alignment', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'background',
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('cl_id', models.IntegerField(default=0, primary_key=True)),
                ('cl_name', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'class',
            },
        ),
        migrations.CreateModel(
            name='Classspell',
            fields=[
                ('clsp_ability', models.CharField(max_length=3)),
                ('clsp_id', models.IntegerField(default=0, primary_key=True)),
                ('clsp_name', models.CharField(max_length=25, primary_key=True)),
            ],
            options={
                'db_table': 'classSpell',
            },
        ),
        migrations.CreateModel(
            name='Classweapon',
            fields=[
                ('clwpn_prof', models.CharField(max_length=1)),
                ('clwpn_name', models.CharField(max_length=25, primary_key=True)),
                ('clwpn_id', models.IntegerField(default=0, primary_key=True)),
            ],
            options={
                'db_table': 'classWeapon',
            },
        ),
        migrations.CreateModel(
            name='Playercharacter',
            fields=[
                ('pc_name', models.CharField(max_length=20)),
                ('pc_key', models.IntegerField(default=0 ,primary_key=True)),
                ('pc_class', models.IntegerField(default=0)),
                ('pc_level', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'playerCharacter',
            },
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('sp_name', models.CharField(max_length=25, primary_key = True)),
                ('sp_slotlevel', models.IntegerField(default=0)),
                ('sp_range', models.IntegerField(default=0)),
                ('sp_castingtype', models.CharField(max_length=25)),
                ('sp_effect', models.CharField(max_length=25)),
                ('sp_die', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'spell',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('u_key', models.IntegerField(default=0, primary_key=True)),
                ('u_name', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('wpn_name', models.CharField(max_length=25 ,primary_key=True)),
                ('wpn_range', models.IntegerField(default=0)),
                ('wpn_damage', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'weapon',
            },
        ),
    ]
